### ISSUE TITLE
Image cropping and model connection (frontend)

### ISSUE THREAD

**Issue by jasozh** [CornellDataScience/sketchy#25]
Branch: `image-to-sketch-frontend`

### Task at Hand
- [ ] There should be a basic html button with no styling that allows users to upload an image.
- [ ] Once uploaded, the image should be displayed and users should be able to crop the image by highlighting a selection.
- [ ] After highlighting a selection, a new basic html button will appear. When pressed, the entire ML model runs from the backend with the image passed in as bytes and coordinates passed into the python function.

### Notes
- Read this: https://www.npmjs.com/package/react-image-crop
